/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package com.omarkarimli.discoextractor.extractor.timeago.patterns;

import com.omarkarimli.discoextractor.extractor.timeago.PatternsHolder;

public class et extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"sekund", "sekundit"},
            MINUTES  /**/ = {"minut", "minutit"},
            HOURS    /**/ = {"tund", "tundi"},
            DAYS     /**/ = {"päev", "päeva"},
            WEEKS    /**/ = {"nädal", "nädalat"},
            MONTHS   /**/ = {"kuu", "kuud"},
            YEARS    /**/ = {"aasta", "aastat"};

    private static final et INSTANCE = new et();

    public static et getInstance() {
        return INSTANCE;
    }

    private et() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}